// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.11.2
// source: common/pb/mvp.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type AddGoodReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodName string  `protobuf:"bytes,1,opt,name=goodName,proto3" json:"goodName,omitempty"`
	Price    float32 `protobuf:"fixed32,2,opt,name=price,proto3" json:"price,omitempty"`
	Type     int64   `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *AddGoodReq) Reset() {
	*x = AddGoodReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_pb_mvp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddGoodReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGoodReq) ProtoMessage() {}

func (x *AddGoodReq) ProtoReflect() protoreflect.Message {
	mi := &file_common_pb_mvp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGoodReq.ProtoReflect.Descriptor instead.
func (*AddGoodReq) Descriptor() ([]byte, []int) {
	return file_common_pb_mvp_proto_rawDescGZIP(), []int{0}
}

func (x *AddGoodReq) GetGoodName() string {
	if x != nil {
		return x.GoodName
	}
	return ""
}

func (x *AddGoodReq) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *AddGoodReq) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

type AddGoodRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddGoodRes) Reset() {
	*x = AddGoodRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_pb_mvp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddGoodRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGoodRes) ProtoMessage() {}

func (x *AddGoodRes) ProtoReflect() protoreflect.Message {
	mi := &file_common_pb_mvp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGoodRes.ProtoReflect.Descriptor instead.
func (*AddGoodRes) Descriptor() ([]byte, []int) {
	return file_common_pb_mvp_proto_rawDescGZIP(), []int{1}
}

type SellGoodReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodName  string  `protobuf:"bytes,1,opt,name=goodName,proto3" json:"goodName,omitempty"`
	SellPrice float32 `protobuf:"fixed32,2,opt,name=sellPrice,proto3" json:"sellPrice,omitempty"`
}

func (x *SellGoodReq) Reset() {
	*x = SellGoodReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_pb_mvp_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SellGoodReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellGoodReq) ProtoMessage() {}

func (x *SellGoodReq) ProtoReflect() protoreflect.Message {
	mi := &file_common_pb_mvp_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellGoodReq.ProtoReflect.Descriptor instead.
func (*SellGoodReq) Descriptor() ([]byte, []int) {
	return file_common_pb_mvp_proto_rawDescGZIP(), []int{2}
}

func (x *SellGoodReq) GetGoodName() string {
	if x != nil {
		return x.GoodName
	}
	return ""
}

func (x *SellGoodReq) GetSellPrice() float32 {
	if x != nil {
		return x.SellPrice
	}
	return 0
}

type SellGoodRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SellGoodRes) Reset() {
	*x = SellGoodRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_pb_mvp_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SellGoodRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellGoodRes) ProtoMessage() {}

func (x *SellGoodRes) ProtoReflect() protoreflect.Message {
	mi := &file_common_pb_mvp_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellGoodRes.ProtoReflect.Descriptor instead.
func (*SellGoodRes) Descriptor() ([]byte, []int) {
	return file_common_pb_mvp_proto_rawDescGZIP(), []int{3}
}

type AddBilliardDeskReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BilliardDeskName string `protobuf:"bytes,1,opt,name=billiardDeskName,proto3" json:"billiardDeskName,omitempty"`
}

func (x *AddBilliardDeskReq) Reset() {
	*x = AddBilliardDeskReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_pb_mvp_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddBilliardDeskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBilliardDeskReq) ProtoMessage() {}

func (x *AddBilliardDeskReq) ProtoReflect() protoreflect.Message {
	mi := &file_common_pb_mvp_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBilliardDeskReq.ProtoReflect.Descriptor instead.
func (*AddBilliardDeskReq) Descriptor() ([]byte, []int) {
	return file_common_pb_mvp_proto_rawDescGZIP(), []int{4}
}

func (x *AddBilliardDeskReq) GetBilliardDeskName() string {
	if x != nil {
		return x.BilliardDeskName
	}
	return ""
}

type AddBilliardDeskRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddBilliardDeskRes) Reset() {
	*x = AddBilliardDeskRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_pb_mvp_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddBilliardDeskRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBilliardDeskRes) ProtoMessage() {}

func (x *AddBilliardDeskRes) ProtoReflect() protoreflect.Message {
	mi := &file_common_pb_mvp_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBilliardDeskRes.ProtoReflect.Descriptor instead.
func (*AddBilliardDeskRes) Descriptor() ([]byte, []int) {
	return file_common_pb_mvp_proto_rawDescGZIP(), []int{5}
}

type BeginPlayBilliardReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BilliardDeskName   string `protobuf:"bytes,1,opt,name=billiardDeskName,proto3" json:"billiardDeskName,omitempty"`
	BeginPlayTimestamp int64  `protobuf:"varint,2,opt,name=beginPlayTimestamp,proto3" json:"beginPlayTimestamp,omitempty"`
}

func (x *BeginPlayBilliardReq) Reset() {
	*x = BeginPlayBilliardReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_pb_mvp_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BeginPlayBilliardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginPlayBilliardReq) ProtoMessage() {}

func (x *BeginPlayBilliardReq) ProtoReflect() protoreflect.Message {
	mi := &file_common_pb_mvp_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginPlayBilliardReq.ProtoReflect.Descriptor instead.
func (*BeginPlayBilliardReq) Descriptor() ([]byte, []int) {
	return file_common_pb_mvp_proto_rawDescGZIP(), []int{6}
}

func (x *BeginPlayBilliardReq) GetBilliardDeskName() string {
	if x != nil {
		return x.BilliardDeskName
	}
	return ""
}

func (x *BeginPlayBilliardReq) GetBeginPlayTimestamp() int64 {
	if x != nil {
		return x.BeginPlayTimestamp
	}
	return 0
}

type BeginPlayBilliardRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BeginPlayBilliardRes) Reset() {
	*x = BeginPlayBilliardRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_pb_mvp_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BeginPlayBilliardRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginPlayBilliardRes) ProtoMessage() {}

func (x *BeginPlayBilliardRes) ProtoReflect() protoreflect.Message {
	mi := &file_common_pb_mvp_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginPlayBilliardRes.ProtoReflect.Descriptor instead.
func (*BeginPlayBilliardRes) Descriptor() ([]byte, []int) {
	return file_common_pb_mvp_proto_rawDescGZIP(), []int{7}
}

type StopPlayBilliardReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BilliardDeskName   string `protobuf:"bytes,1,opt,name=billiardDeskName,proto3" json:"billiardDeskName,omitempty"`
	BeginPlayTimestamp int64  `protobuf:"varint,2,opt,name=beginPlayTimestamp,proto3" json:"beginPlayTimestamp,omitempty"`
	StopPlayTimestamp  int64  `protobuf:"varint,3,opt,name=stopPlayTimestamp,proto3" json:"stopPlayTimestamp,omitempty"`
}

func (x *StopPlayBilliardReq) Reset() {
	*x = StopPlayBilliardReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_pb_mvp_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopPlayBilliardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopPlayBilliardReq) ProtoMessage() {}

func (x *StopPlayBilliardReq) ProtoReflect() protoreflect.Message {
	mi := &file_common_pb_mvp_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopPlayBilliardReq.ProtoReflect.Descriptor instead.
func (*StopPlayBilliardReq) Descriptor() ([]byte, []int) {
	return file_common_pb_mvp_proto_rawDescGZIP(), []int{8}
}

func (x *StopPlayBilliardReq) GetBilliardDeskName() string {
	if x != nil {
		return x.BilliardDeskName
	}
	return ""
}

func (x *StopPlayBilliardReq) GetBeginPlayTimestamp() int64 {
	if x != nil {
		return x.BeginPlayTimestamp
	}
	return 0
}

func (x *StopPlayBilliardReq) GetStopPlayTimestamp() int64 {
	if x != nil {
		return x.StopPlayTimestamp
	}
	return 0
}

type StopPlayBilliardRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StopPlayBilliardRes) Reset() {
	*x = StopPlayBilliardRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_pb_mvp_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopPlayBilliardRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopPlayBilliardRes) ProtoMessage() {}

func (x *StopPlayBilliardRes) ProtoReflect() protoreflect.Message {
	mi := &file_common_pb_mvp_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopPlayBilliardRes.ProtoReflect.Descriptor instead.
func (*StopPlayBilliardRes) Descriptor() ([]byte, []int) {
	return file_common_pb_mvp_proto_rawDescGZIP(), []int{9}
}

type AttachGood struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *AttachGood) Reset() {
	*x = AttachGood{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_pb_mvp_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttachGood) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachGood) ProtoMessage() {}

func (x *AttachGood) ProtoReflect() protoreflect.Message {
	mi := &file_common_pb_mvp_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachGood.ProtoReflect.Descriptor instead.
func (*AttachGood) Descriptor() ([]byte, []int) {
	return file_common_pb_mvp_proto_rawDescGZIP(), []int{10}
}

func (x *AttachGood) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Good struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string                     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	AttachGoods map[int64]*AttachGoodArray `protobuf:"bytes,2,rep,name=attachGoods,proto3" json:"attachGoods,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Good) Reset() {
	*x = Good{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_pb_mvp_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Good) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Good) ProtoMessage() {}

func (x *Good) ProtoReflect() protoreflect.Message {
	mi := &file_common_pb_mvp_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Good.ProtoReflect.Descriptor instead.
func (*Good) Descriptor() ([]byte, []int) {
	return file_common_pb_mvp_proto_rawDescGZIP(), []int{11}
}

func (x *Good) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Good) GetAttachGoods() map[int64]*AttachGoodArray {
	if x != nil {
		return x.AttachGoods
	}
	return nil
}

type AttachGoodArray struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AttachGoods []*AttachGood `protobuf:"bytes,1,rep,name=attachGoods,proto3" json:"attachGoods,omitempty"`
}

func (x *AttachGoodArray) Reset() {
	*x = AttachGoodArray{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_pb_mvp_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttachGoodArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachGoodArray) ProtoMessage() {}

func (x *AttachGoodArray) ProtoReflect() protoreflect.Message {
	mi := &file_common_pb_mvp_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachGoodArray.ProtoReflect.Descriptor instead.
func (*AttachGoodArray) Descriptor() ([]byte, []int) {
	return file_common_pb_mvp_proto_rawDescGZIP(), []int{12}
}

func (x *AttachGoodArray) GetAttachGoods() []*AttachGood {
	if x != nil {
		return x.AttachGoods
	}
	return nil
}

type OrderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Goods []*Good `protobuf:"bytes,1,rep,name=goods,proto3" json:"goods,omitempty"`
}

func (x *OrderReq) Reset() {
	*x = OrderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_pb_mvp_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderReq) ProtoMessage() {}

func (x *OrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_common_pb_mvp_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderReq.ProtoReflect.Descriptor instead.
func (*OrderReq) Descriptor() ([]byte, []int) {
	return file_common_pb_mvp_proto_rawDescGZIP(), []int{13}
}

func (x *OrderReq) GetGoods() []*Good {
	if x != nil {
		return x.Goods
	}
	return nil
}

type OrderRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderID int64 `protobuf:"varint,1,opt,name=orderID,proto3" json:"orderID,omitempty"`
}

func (x *OrderRes) Reset() {
	*x = OrderRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_pb_mvp_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderRes) ProtoMessage() {}

func (x *OrderRes) ProtoReflect() protoreflect.Message {
	mi := &file_common_pb_mvp_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderRes.ProtoReflect.Descriptor instead.
func (*OrderRes) Descriptor() ([]byte, []int) {
	return file_common_pb_mvp_proto_rawDescGZIP(), []int{14}
}

func (x *OrderRes) GetOrderID() int64 {
	if x != nil {
		return x.OrderID
	}
	return 0
}

type GetOrderGoodsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderID int64 `protobuf:"varint,1,opt,name=orderID,proto3" json:"orderID,omitempty"`
}

func (x *GetOrderGoodsReq) Reset() {
	*x = GetOrderGoodsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_pb_mvp_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrderGoodsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderGoodsReq) ProtoMessage() {}

func (x *GetOrderGoodsReq) ProtoReflect() protoreflect.Message {
	mi := &file_common_pb_mvp_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderGoodsReq.ProtoReflect.Descriptor instead.
func (*GetOrderGoodsReq) Descriptor() ([]byte, []int) {
	return file_common_pb_mvp_proto_rawDescGZIP(), []int{15}
}

func (x *GetOrderGoodsReq) GetOrderID() int64 {
	if x != nil {
		return x.OrderID
	}
	return 0
}

type GetOrderGoodsRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Goods []*Good `protobuf:"bytes,1,rep,name=goods,proto3" json:"goods,omitempty"`
}

func (x *GetOrderGoodsRes) Reset() {
	*x = GetOrderGoodsRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_pb_mvp_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrderGoodsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderGoodsRes) ProtoMessage() {}

func (x *GetOrderGoodsRes) ProtoReflect() protoreflect.Message {
	mi := &file_common_pb_mvp_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderGoodsRes.ProtoReflect.Descriptor instead.
func (*GetOrderGoodsRes) Descriptor() ([]byte, []int) {
	return file_common_pb_mvp_proto_rawDescGZIP(), []int{16}
}

func (x *GetOrderGoodsRes) GetGoods() []*Good {
	if x != nil {
		return x.Goods
	}
	return nil
}

type AddGoodTypeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TypeName string `protobuf:"bytes,1,opt,name=typeName,proto3" json:"typeName,omitempty"`
}

func (x *AddGoodTypeReq) Reset() {
	*x = AddGoodTypeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_pb_mvp_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddGoodTypeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGoodTypeReq) ProtoMessage() {}

func (x *AddGoodTypeReq) ProtoReflect() protoreflect.Message {
	mi := &file_common_pb_mvp_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGoodTypeReq.ProtoReflect.Descriptor instead.
func (*AddGoodTypeReq) Descriptor() ([]byte, []int) {
	return file_common_pb_mvp_proto_rawDescGZIP(), []int{17}
}

func (x *AddGoodTypeReq) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

type AddGoodTypeRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddGoodTypeRes) Reset() {
	*x = AddGoodTypeRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_pb_mvp_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddGoodTypeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGoodTypeRes) ProtoMessage() {}

func (x *AddGoodTypeRes) ProtoReflect() protoreflect.Message {
	mi := &file_common_pb_mvp_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGoodTypeRes.ProtoReflect.Descriptor instead.
func (*AddGoodTypeRes) Descriptor() ([]byte, []int) {
	return file_common_pb_mvp_proto_rawDescGZIP(), []int{18}
}

type CheckoutReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderID int64 `protobuf:"varint,1,opt,name=orderID,proto3" json:"orderID,omitempty"`
}

func (x *CheckoutReq) Reset() {
	*x = CheckoutReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_pb_mvp_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckoutReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutReq) ProtoMessage() {}

func (x *CheckoutReq) ProtoReflect() protoreflect.Message {
	mi := &file_common_pb_mvp_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutReq.ProtoReflect.Descriptor instead.
func (*CheckoutReq) Descriptor() ([]byte, []int) {
	return file_common_pb_mvp_proto_rawDescGZIP(), []int{19}
}

func (x *CheckoutReq) GetOrderID() int64 {
	if x != nil {
		return x.OrderID
	}
	return 0
}

type CheckoutRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Price float32 `protobuf:"fixed32,1,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *CheckoutRes) Reset() {
	*x = CheckoutRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_pb_mvp_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckoutRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutRes) ProtoMessage() {}

func (x *CheckoutRes) ProtoReflect() protoreflect.Message {
	mi := &file_common_pb_mvp_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutRes.ProtoReflect.Descriptor instead.
func (*CheckoutRes) Descriptor() ([]byte, []int) {
	return file_common_pb_mvp_proto_rawDescGZIP(), []int{20}
}

func (x *CheckoutRes) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_common_pb_mvp_proto protoreflect.FileDescriptor

var file_common_pb_mvp_proto_rawDesc = []byte{
	0x0a, 0x13, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x62, 0x2f, 0x6d, 0x76, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x52, 0x0a, 0x0a, 0x41, 0x64, 0x64,
	0x47, 0x6f, 0x6f, 0x64, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x6f, 0x6f, 0x64, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x6f, 0x6f, 0x64, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x0c, 0x0a,
	0x0a, 0x41, 0x64, 0x64, 0x47, 0x6f, 0x6f, 0x64, 0x52, 0x65, 0x73, 0x22, 0x47, 0x0a, 0x0b, 0x53,
	0x65, 0x6c, 0x6c, 0x47, 0x6f, 0x6f, 0x64, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x6f,
	0x6f, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x6f,
	0x6f, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x6c, 0x6c, 0x50, 0x72,
	0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x73, 0x65, 0x6c, 0x6c, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x22, 0x0d, 0x0a, 0x0b, 0x53, 0x65, 0x6c, 0x6c, 0x47, 0x6f, 0x6f, 0x64,
	0x52, 0x65, 0x73, 0x22, 0x40, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x42, 0x69, 0x6c, 0x6c, 0x69, 0x61,
	0x72, 0x64, 0x44, 0x65, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x2a, 0x0a, 0x10, 0x62, 0x69, 0x6c,
	0x6c, 0x69, 0x61, 0x72, 0x64, 0x44, 0x65, 0x73, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x10, 0x62, 0x69, 0x6c, 0x6c, 0x69, 0x61, 0x72, 0x64, 0x44, 0x65, 0x73,
	0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x14, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x42, 0x69, 0x6c, 0x6c,
	0x69, 0x61, 0x72, 0x64, 0x44, 0x65, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x22, 0x72, 0x0a, 0x14, 0x42,
	0x65, 0x67, 0x69, 0x6e, 0x50, 0x6c, 0x61, 0x79, 0x42, 0x69, 0x6c, 0x6c, 0x69, 0x61, 0x72, 0x64,
	0x52, 0x65, 0x71, 0x12, 0x2a, 0x0a, 0x10, 0x62, 0x69, 0x6c, 0x6c, 0x69, 0x61, 0x72, 0x64, 0x44,
	0x65, 0x73, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x62,
	0x69, 0x6c, 0x6c, 0x69, 0x61, 0x72, 0x64, 0x44, 0x65, 0x73, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x2e, 0x0a, 0x12, 0x62, 0x65, 0x67, 0x69, 0x6e, 0x50, 0x6c, 0x61, 0x79, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x12, 0x62, 0x65, 0x67,
	0x69, 0x6e, 0x50, 0x6c, 0x61, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22,
	0x16, 0x0a, 0x14, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x50, 0x6c, 0x61, 0x79, 0x42, 0x69, 0x6c, 0x6c,
	0x69, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x22, 0x9f, 0x01, 0x0a, 0x13, 0x53, 0x74, 0x6f, 0x70,
	0x50, 0x6c, 0x61, 0x79, 0x42, 0x69, 0x6c, 0x6c, 0x69, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x12,
	0x2a, 0x0a, 0x10, 0x62, 0x69, 0x6c, 0x6c, 0x69, 0x61, 0x72, 0x64, 0x44, 0x65, 0x73, 0x6b, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x62, 0x69, 0x6c, 0x6c, 0x69,
	0x61, 0x72, 0x64, 0x44, 0x65, 0x73, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2e, 0x0a, 0x12, 0x62,
	0x65, 0x67, 0x69, 0x6e, 0x50, 0x6c, 0x61, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x12, 0x62, 0x65, 0x67, 0x69, 0x6e, 0x50, 0x6c,
	0x61, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x2c, 0x0a, 0x11, 0x73,
	0x74, 0x6f, 0x70, 0x50, 0x6c, 0x61, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x73, 0x74, 0x6f, 0x70, 0x50, 0x6c, 0x61, 0x79,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x15, 0x0a, 0x13, 0x53, 0x74, 0x6f,
	0x70, 0x50, 0x6c, 0x61, 0x79, 0x42, 0x69, 0x6c, 0x6c, 0x69, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73,
	0x22, 0x20, 0x0a, 0x0a, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x47, 0x6f, 0x6f, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0xac, 0x01, 0x0a, 0x04, 0x47, 0x6f, 0x6f, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x3b, 0x0a, 0x0b, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x2e, 0x41,
	0x74, 0x74, 0x61, 0x63, 0x68, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x0b, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x1a, 0x53, 0x0a, 0x10,
	0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x29, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x47, 0x6f, 0x6f,
	0x64, 0x41, 0x72, 0x72, 0x61, 0x79, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38,
	0x01, 0x22, 0x43, 0x0a, 0x0f, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x47, 0x6f, 0x6f, 0x64, 0x41,
	0x72, 0x72, 0x61, 0x79, 0x12, 0x30, 0x0a, 0x0b, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x47, 0x6f,
	0x6f, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x41,
	0x74, 0x74, 0x61, 0x63, 0x68, 0x47, 0x6f, 0x6f, 0x64, 0x52, 0x0b, 0x61, 0x74, 0x74, 0x61, 0x63,
	0x68, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x22, 0x2a, 0x0a, 0x08, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x12, 0x1e, 0x0a, 0x05, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x52, 0x05, 0x67, 0x6f, 0x6f,
	0x64, 0x73, 0x22, 0x24, 0x0a, 0x08, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x44, 0x22, 0x2c, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x49, 0x44, 0x22, 0x32, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x05, 0x67, 0x6f,
	0x6f, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x47,
	0x6f, 0x6f, 0x64, 0x52, 0x05, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x22, 0x2c, 0x0a, 0x0e, 0x41, 0x64,
	0x64, 0x47, 0x6f, 0x6f, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08,
	0x74, 0x79, 0x70, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x74, 0x79, 0x70, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x10, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x47,
	0x6f, 0x6f, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x73, 0x22, 0x27, 0x0a, 0x0b, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x49, 0x44, 0x22, 0x23, 0x0a, 0x0b, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x52,
	0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x32, 0xf7, 0x03, 0x0a, 0x03, 0x4d, 0x76, 0x70,
	0x12, 0x29, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x47, 0x6f, 0x6f, 0x64, 0x12, 0x0e, 0x2e, 0x70, 0x62,
	0x2e, 0x41, 0x64, 0x64, 0x47, 0x6f, 0x6f, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x70, 0x62,
	0x2e, 0x41, 0x64, 0x64, 0x47, 0x6f, 0x6f, 0x64, 0x52, 0x65, 0x73, 0x12, 0x41, 0x0a, 0x0f, 0x41,
	0x64, 0x64, 0x42, 0x69, 0x6c, 0x6c, 0x69, 0x61, 0x72, 0x64, 0x44, 0x65, 0x73, 0x6b, 0x12, 0x16,
	0x2e, 0x70, 0x62, 0x2e, 0x41, 0x64, 0x64, 0x42, 0x69, 0x6c, 0x6c, 0x69, 0x61, 0x72, 0x64, 0x44,
	0x65, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x64, 0x64, 0x42,
	0x69, 0x6c, 0x6c, 0x69, 0x61, 0x72, 0x64, 0x44, 0x65, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x12, 0x2c,
	0x0a, 0x08, 0x53, 0x65, 0x6c, 0x6c, 0x47, 0x6f, 0x6f, 0x64, 0x12, 0x0f, 0x2e, 0x70, 0x62, 0x2e,
	0x53, 0x65, 0x6c, 0x6c, 0x47, 0x6f, 0x6f, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x70, 0x62,
	0x2e, 0x53, 0x65, 0x6c, 0x6c, 0x47, 0x6f, 0x6f, 0x64, 0x52, 0x65, 0x73, 0x12, 0x47, 0x0a, 0x11,
	0x42, 0x65, 0x67, 0x69, 0x6e, 0x50, 0x6c, 0x61, 0x79, 0x42, 0x69, 0x6c, 0x6c, 0x69, 0x61, 0x72,
	0x64, 0x12, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x50, 0x6c, 0x61, 0x79,
	0x42, 0x69, 0x6c, 0x6c, 0x69, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x70, 0x62,
	0x2e, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x50, 0x6c, 0x61, 0x79, 0x42, 0x69, 0x6c, 0x6c, 0x69, 0x61,
	0x72, 0x64, 0x52, 0x65, 0x73, 0x12, 0x44, 0x0a, 0x10, 0x53, 0x74, 0x6f, 0x70, 0x50, 0x6c, 0x61,
	0x79, 0x42, 0x69, 0x6c, 0x6c, 0x69, 0x61, 0x72, 0x64, 0x12, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x53,
	0x74, 0x6f, 0x70, 0x50, 0x6c, 0x61, 0x79, 0x42, 0x69, 0x6c, 0x6c, 0x69, 0x61, 0x72, 0x64, 0x52,
	0x65, 0x71, 0x1a, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x50, 0x6c, 0x61, 0x79,
	0x42, 0x69, 0x6c, 0x6c, 0x69, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x12, 0x23, 0x0a, 0x05, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x12, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x12, 0x3b, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x47, 0x6f, 0x6f, 0x64,
	0x73, 0x12, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x47,
	0x6f, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x73, 0x12, 0x35, 0x0a,
	0x0b, 0x41, 0x64, 0x64, 0x47, 0x6f, 0x6f, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x2e, 0x70,
	0x62, 0x2e, 0x41, 0x64, 0x64, 0x47, 0x6f, 0x6f, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x71,
	0x1a, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x64, 0x64, 0x47, 0x6f, 0x6f, 0x64, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x65, 0x73, 0x12, 0x2c, 0x0a, 0x08, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74,
	0x12, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x52, 0x65,
	0x71, 0x1a, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x52,
	0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_pb_mvp_proto_rawDescOnce sync.Once
	file_common_pb_mvp_proto_rawDescData = file_common_pb_mvp_proto_rawDesc
)

func file_common_pb_mvp_proto_rawDescGZIP() []byte {
	file_common_pb_mvp_proto_rawDescOnce.Do(func() {
		file_common_pb_mvp_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_pb_mvp_proto_rawDescData)
	})
	return file_common_pb_mvp_proto_rawDescData
}

var file_common_pb_mvp_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_common_pb_mvp_proto_goTypes = []interface{}{
	(*AddGoodReq)(nil),           // 0: pb.AddGoodReq
	(*AddGoodRes)(nil),           // 1: pb.AddGoodRes
	(*SellGoodReq)(nil),          // 2: pb.SellGoodReq
	(*SellGoodRes)(nil),          // 3: pb.SellGoodRes
	(*AddBilliardDeskReq)(nil),   // 4: pb.AddBilliardDeskReq
	(*AddBilliardDeskRes)(nil),   // 5: pb.AddBilliardDeskRes
	(*BeginPlayBilliardReq)(nil), // 6: pb.BeginPlayBilliardReq
	(*BeginPlayBilliardRes)(nil), // 7: pb.BeginPlayBilliardRes
	(*StopPlayBilliardReq)(nil),  // 8: pb.StopPlayBilliardReq
	(*StopPlayBilliardRes)(nil),  // 9: pb.StopPlayBilliardRes
	(*AttachGood)(nil),           // 10: pb.AttachGood
	(*Good)(nil),                 // 11: pb.Good
	(*AttachGoodArray)(nil),      // 12: pb.AttachGoodArray
	(*OrderReq)(nil),             // 13: pb.OrderReq
	(*OrderRes)(nil),             // 14: pb.OrderRes
	(*GetOrderGoodsReq)(nil),     // 15: pb.GetOrderGoodsReq
	(*GetOrderGoodsRes)(nil),     // 16: pb.GetOrderGoodsRes
	(*AddGoodTypeReq)(nil),       // 17: pb.AddGoodTypeReq
	(*AddGoodTypeRes)(nil),       // 18: pb.AddGoodTypeRes
	(*CheckoutReq)(nil),          // 19: pb.CheckoutReq
	(*CheckoutRes)(nil),          // 20: pb.CheckoutRes
	nil,                          // 21: pb.Good.AttachGoodsEntry
}
var file_common_pb_mvp_proto_depIdxs = []int32{
	21, // 0: pb.Good.attachGoods:type_name -> pb.Good.AttachGoodsEntry
	10, // 1: pb.AttachGoodArray.attachGoods:type_name -> pb.AttachGood
	11, // 2: pb.OrderReq.goods:type_name -> pb.Good
	11, // 3: pb.GetOrderGoodsRes.goods:type_name -> pb.Good
	12, // 4: pb.Good.AttachGoodsEntry.value:type_name -> pb.AttachGoodArray
	0,  // 5: pb.Mvp.AddGood:input_type -> pb.AddGoodReq
	4,  // 6: pb.Mvp.AddBilliardDesk:input_type -> pb.AddBilliardDeskReq
	2,  // 7: pb.Mvp.SellGood:input_type -> pb.SellGoodReq
	6,  // 8: pb.Mvp.BeginPlayBilliard:input_type -> pb.BeginPlayBilliardReq
	8,  // 9: pb.Mvp.StopPlayBilliard:input_type -> pb.StopPlayBilliardReq
	13, // 10: pb.Mvp.Order:input_type -> pb.OrderReq
	15, // 11: pb.Mvp.GetOrderGoods:input_type -> pb.GetOrderGoodsReq
	17, // 12: pb.Mvp.AddGoodType:input_type -> pb.AddGoodTypeReq
	19, // 13: pb.Mvp.Checkout:input_type -> pb.CheckoutReq
	1,  // 14: pb.Mvp.AddGood:output_type -> pb.AddGoodRes
	5,  // 15: pb.Mvp.AddBilliardDesk:output_type -> pb.AddBilliardDeskRes
	3,  // 16: pb.Mvp.SellGood:output_type -> pb.SellGoodRes
	7,  // 17: pb.Mvp.BeginPlayBilliard:output_type -> pb.BeginPlayBilliardRes
	9,  // 18: pb.Mvp.StopPlayBilliard:output_type -> pb.StopPlayBilliardRes
	14, // 19: pb.Mvp.Order:output_type -> pb.OrderRes
	16, // 20: pb.Mvp.GetOrderGoods:output_type -> pb.GetOrderGoodsRes
	18, // 21: pb.Mvp.AddGoodType:output_type -> pb.AddGoodTypeRes
	20, // 22: pb.Mvp.Checkout:output_type -> pb.CheckoutRes
	14, // [14:23] is the sub-list for method output_type
	5,  // [5:14] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_common_pb_mvp_proto_init() }
func file_common_pb_mvp_proto_init() {
	if File_common_pb_mvp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_pb_mvp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddGoodReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_pb_mvp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddGoodRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_pb_mvp_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SellGoodReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_pb_mvp_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SellGoodRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_pb_mvp_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddBilliardDeskReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_pb_mvp_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddBilliardDeskRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_pb_mvp_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BeginPlayBilliardReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_pb_mvp_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BeginPlayBilliardRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_pb_mvp_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopPlayBilliardReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_pb_mvp_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopPlayBilliardRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_pb_mvp_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttachGood); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_pb_mvp_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Good); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_pb_mvp_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttachGoodArray); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_pb_mvp_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_pb_mvp_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_pb_mvp_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrderGoodsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_pb_mvp_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrderGoodsRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_pb_mvp_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddGoodTypeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_pb_mvp_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddGoodTypeRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_pb_mvp_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckoutReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_pb_mvp_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckoutRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_pb_mvp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_pb_mvp_proto_goTypes,
		DependencyIndexes: file_common_pb_mvp_proto_depIdxs,
		MessageInfos:      file_common_pb_mvp_proto_msgTypes,
	}.Build()
	File_common_pb_mvp_proto = out.File
	file_common_pb_mvp_proto_rawDesc = nil
	file_common_pb_mvp_proto_goTypes = nil
	file_common_pb_mvp_proto_depIdxs = nil
}
