// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: common/pb/mvp.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type FavorType int32

const (
	FavorType_NONE           FavorType = 0 // 无
	FavorType_REBATE         FavorType = 1 // 打折
	FavorType_FULL_REDUCTION FavorType = 2 // 满减
	FavorType_FREE           FavorType = 3 // 免单
)

// Enum value maps for FavorType.
var (
	FavorType_name = map[int32]string{
		0: "NONE",
		1: "REBATE",
		2: "FULL_REDUCTION",
		3: "FREE",
	}
	FavorType_value = map[string]int32{
		"NONE":           0,
		"REBATE":         1,
		"FULL_REDUCTION": 2,
		"FREE":           3,
	}
)

func (x FavorType) Enum() *FavorType {
	p := new(FavorType)
	*p = x
	return p
}

func (x FavorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FavorType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_pb_mvp_proto_enumTypes[0].Descriptor()
}

func (FavorType) Type() protoreflect.EnumType {
	return &file_common_pb_mvp_proto_enumTypes[0]
}

func (x FavorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FavorType.Descriptor instead.
func (FavorType) EnumDescriptor() ([]byte, []int) {
	return file_common_pb_mvp_proto_rawDescGZIP(), []int{0}
}

type PriceRuleType int32

const (
	PriceRuleType_Time  PriceRuleType = 0
	PriceRuleType_Count PriceRuleType = 1
)

// Enum value maps for PriceRuleType.
var (
	PriceRuleType_name = map[int32]string{
		0: "Time",
		1: "Count",
	}
	PriceRuleType_value = map[string]int32{
		"Time":  0,
		"Count": 1,
	}
)

func (x PriceRuleType) Enum() *PriceRuleType {
	p := new(PriceRuleType)
	*p = x
	return p
}

func (x PriceRuleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PriceRuleType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_pb_mvp_proto_enumTypes[1].Descriptor()
}

func (PriceRuleType) Type() protoreflect.EnumType {
	return &file_common_pb_mvp_proto_enumTypes[1]
}

func (x PriceRuleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PriceRuleType.Descriptor instead.
func (PriceRuleType) EnumDescriptor() ([]byte, []int) {
	return file_common_pb_mvp_proto_rawDescGZIP(), []int{1}
}

type ElementType int32

const (
	ElementType_Main   ElementType = 0
	ElementType_Attach ElementType = 1
)

// Enum value maps for ElementType.
var (
	ElementType_name = map[int32]string{
		0: "Main",
		1: "Attach",
	}
	ElementType_value = map[string]int32{
		"Main":   0,
		"Attach": 1,
	}
)

func (x ElementType) Enum() *ElementType {
	p := new(ElementType)
	*p = x
	return p
}

func (x ElementType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ElementType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_pb_mvp_proto_enumTypes[2].Descriptor()
}

func (ElementType) Type() protoreflect.EnumType {
	return &file_common_pb_mvp_proto_enumTypes[2]
}

func (x ElementType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ElementType.Descriptor instead.
func (ElementType) EnumDescriptor() ([]byte, []int) {
	return file_common_pb_mvp_proto_rawDescGZIP(), []int{2}
}

// ---------------------- instance 相关 ----------------------
type ExpenseInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NonFavorExpense   float64 `protobuf:"fixed64,1,opt,name=nonFavorExpense,proto3" json:"nonFavorExpense,omitempty"`    // 未打折费用
	CheckOutTimestamp int64   `protobuf:"varint,2,opt,name=checkOutTimestamp,proto3" json:"checkOutTimestamp,omitempty"` // 结账时间
	Expense           float64 `protobuf:"fixed64,3,opt,name=expense,proto3" json:"expense,omitempty"`                    // 打折后费用
}

func (x *ExpenseInfo) Reset() {
	*x = ExpenseInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_pb_mvp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExpenseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpenseInfo) ProtoMessage() {}

func (x *ExpenseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_pb_mvp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpenseInfo.ProtoReflect.Descriptor instead.
func (*ExpenseInfo) Descriptor() ([]byte, []int) {
	return file_common_pb_mvp_proto_rawDescGZIP(), []int{0}
}

func (x *ExpenseInfo) GetNonFavorExpense() float64 {
	if x != nil {
		return x.NonFavorExpense
	}
	return 0
}

func (x *ExpenseInfo) GetCheckOutTimestamp() int64 {
	if x != nil {
		return x.CheckOutTimestamp
	}
	return 0
}

func (x *ExpenseInfo) GetExpense() float64 {
	if x != nil {
		return x.Expense
	}
	return 0
}

type Order struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Desk        *Desk        `protobuf:"bytes,2,opt,name=desk,proto3" json:"desk,omitempty"`
	Favors      []*Favor     `protobuf:"bytes,3,rep,name=favors,proto3" json:"favors,omitempty"`
	ExpenseInfo *ExpenseInfo `protobuf:"bytes,4,opt,name=expenseInfo,proto3" json:"expenseInfo,omitempty"`
}

func (x *Order) Reset() {
	*x = Order{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_pb_mvp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_common_pb_mvp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_common_pb_mvp_proto_rawDescGZIP(), []int{1}
}

func (x *Order) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Order) GetDesk() *Desk {
	if x != nil {
		return x.Desk
	}
	return nil
}

func (x *Order) GetFavors() []*Favor {
	if x != nil {
		return x.Favors
	}
	return nil
}

func (x *Order) GetExpenseInfo() *ExpenseInfo {
	if x != nil {
		return x.ExpenseInfo
	}
	return nil
}

type Desk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             int64        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Space          *Space       `protobuf:"bytes,2,opt,name=space,proto3" json:"space,omitempty"`
	StartTimestamp int64        `protobuf:"varint,3,opt,name=startTimestamp,proto3" json:"startTimestamp,omitempty"`
	EndTimestamp   int64        `protobuf:"varint,4,opt,name=endTimestamp,proto3" json:"endTimestamp,omitempty"`
	Goods          []*Good      `protobuf:"bytes,5,rep,name=goods,proto3" json:"goods,omitempty"`
	Favors         []*Favor     `protobuf:"bytes,6,rep,name=favors,proto3" json:"favors,omitempty"`
	ExpenseInfo    *ExpenseInfo `protobuf:"bytes,7,opt,name=expenseInfo,proto3" json:"expenseInfo,omitempty"`
}

func (x *Desk) Reset() {
	*x = Desk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_pb_mvp_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Desk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Desk) ProtoMessage() {}

func (x *Desk) ProtoReflect() protoreflect.Message {
	mi := &file_common_pb_mvp_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Desk.ProtoReflect.Descriptor instead.
func (*Desk) Descriptor() ([]byte, []int) {
	return file_common_pb_mvp_proto_rawDescGZIP(), []int{2}
}

func (x *Desk) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Desk) GetSpace() *Space {
	if x != nil {
		return x.Space
	}
	return nil
}

func (x *Desk) GetStartTimestamp() int64 {
	if x != nil {
		return x.StartTimestamp
	}
	return 0
}

func (x *Desk) GetEndTimestamp() int64 {
	if x != nil {
		return x.EndTimestamp
	}
	return 0
}

func (x *Desk) GetGoods() []*Good {
	if x != nil {
		return x.Goods
	}
	return nil
}

func (x *Desk) GetFavors() []*Favor {
	if x != nil {
		return x.Favors
	}
	return nil
}

func (x *Desk) GetExpenseInfo() *ExpenseInfo {
	if x != nil {
		return x.ExpenseInfo
	}
	return nil
}

type Good struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             int64        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MainElement    *Element     `protobuf:"bytes,2,opt,name=mainElement,proto3" json:"mainElement,omitempty"`
	AttachElements []*Element   `protobuf:"bytes,3,rep,name=attachElements,proto3" json:"attachElements,omitempty"`
	Favors         []*Favor     `protobuf:"bytes,4,rep,name=favors,proto3" json:"favors,omitempty"`
	ExpenseInfo    *ExpenseInfo `protobuf:"bytes,5,opt,name=expenseInfo,proto3" json:"expenseInfo,omitempty"`
}

func (x *Good) Reset() {
	*x = Good{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_pb_mvp_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Good) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Good) ProtoMessage() {}

func (x *Good) ProtoReflect() protoreflect.Message {
	mi := &file_common_pb_mvp_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Good.ProtoReflect.Descriptor instead.
func (*Good) Descriptor() ([]byte, []int) {
	return file_common_pb_mvp_proto_rawDescGZIP(), []int{3}
}

func (x *Good) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Good) GetMainElement() *Element {
	if x != nil {
		return x.MainElement
	}
	return nil
}

func (x *Good) GetAttachElements() []*Element {
	if x != nil {
		return x.AttachElements
	}
	return nil
}

func (x *Good) GetFavors() []*Favor {
	if x != nil {
		return x.Favors
	}
	return nil
}

func (x *Good) GetExpenseInfo() *ExpenseInfo {
	if x != nil {
		return x.ExpenseInfo
	}
	return nil
}

type Space struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name          string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Num           int64         `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	Price         float64       `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	PriceRuleType PriceRuleType `protobuf:"varint,4,opt,name=priceRuleType,proto3,enum=pb.PriceRuleType" json:"priceRuleType,omitempty"`
}

func (x *Space) Reset() {
	*x = Space{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_pb_mvp_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Space) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Space) ProtoMessage() {}

func (x *Space) ProtoReflect() protoreflect.Message {
	mi := &file_common_pb_mvp_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Space.ProtoReflect.Descriptor instead.
func (*Space) Descriptor() ([]byte, []int) {
	return file_common_pb_mvp_proto_rawDescGZIP(), []int{4}
}

func (x *Space) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Space) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *Space) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Space) GetPriceRuleType() PriceRuleType {
	if x != nil {
		return x.PriceRuleType
	}
	return PriceRuleType_Time
}

type GoodClass struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Goods []*Good `protobuf:"bytes,2,rep,name=goods,proto3" json:"goods,omitempty"`
}

func (x *GoodClass) Reset() {
	*x = GoodClass{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_pb_mvp_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodClass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodClass) ProtoMessage() {}

func (x *GoodClass) ProtoReflect() protoreflect.Message {
	mi := &file_common_pb_mvp_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodClass.ProtoReflect.Descriptor instead.
func (*GoodClass) Descriptor() ([]byte, []int) {
	return file_common_pb_mvp_proto_rawDescGZIP(), []int{5}
}

func (x *GoodClass) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GoodClass) GetGoods() []*Good {
	if x != nil {
		return x.Goods
	}
	return nil
}

type Element struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type      ElementType `protobuf:"varint,2,opt,name=type,proto3,enum=pb.ElementType" json:"type,omitempty"`
	SizeInfos []*SizeInfo `protobuf:"bytes,3,rep,name=sizeInfos,proto3" json:"sizeInfos,omitempty"`
}

func (x *Element) Reset() {
	*x = Element{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_pb_mvp_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Element) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Element) ProtoMessage() {}

func (x *Element) ProtoReflect() protoreflect.Message {
	mi := &file_common_pb_mvp_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Element.ProtoReflect.Descriptor instead.
func (*Element) Descriptor() ([]byte, []int) {
	return file_common_pb_mvp_proto_rawDescGZIP(), []int{6}
}

func (x *Element) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Element) GetType() ElementType {
	if x != nil {
		return x.Type
	}
	return ElementType_Main
}

func (x *Element) GetSizeInfos() []*SizeInfo {
	if x != nil {
		return x.SizeInfos
	}
	return nil
}

type SizeInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Size             string  `protobuf:"bytes,1,opt,name=size,proto3" json:"size,omitempty"`
	Price            float64 `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	PictureStorePath string  `protobuf:"bytes,3,opt,name=pictureStorePath,proto3" json:"pictureStorePath,omitempty"`
	IsSelected       bool    `protobuf:"varint,4,opt,name=isSelected,proto3" json:"isSelected,omitempty"`
}

func (x *SizeInfo) Reset() {
	*x = SizeInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_pb_mvp_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SizeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SizeInfo) ProtoMessage() {}

func (x *SizeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_pb_mvp_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SizeInfo.ProtoReflect.Descriptor instead.
func (*SizeInfo) Descriptor() ([]byte, []int) {
	return file_common_pb_mvp_proto_rawDescGZIP(), []int{7}
}

func (x *SizeInfo) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *SizeInfo) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *SizeInfo) GetPictureStorePath() string {
	if x != nil {
		return x.PictureStorePath
	}
	return ""
}

func (x *SizeInfo) GetIsSelected() bool {
	if x != nil {
		return x.IsSelected
	}
	return false
}

type Favor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FavorType  FavorType `protobuf:"varint,1,opt,name=FavorType,proto3,enum=pb.FavorType" json:"FavorType,omitempty"`
	Parameters []string  `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty"`
}

func (x *Favor) Reset() {
	*x = Favor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_pb_mvp_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Favor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Favor) ProtoMessage() {}

func (x *Favor) ProtoReflect() protoreflect.Message {
	mi := &file_common_pb_mvp_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Favor.ProtoReflect.Descriptor instead.
func (*Favor) Descriptor() ([]byte, []int) {
	return file_common_pb_mvp_proto_rawDescGZIP(), []int{8}
}

func (x *Favor) GetFavorType() FavorType {
	if x != nil {
		return x.FavorType
	}
	return FavorType_NONE
}

func (x *Favor) GetParameters() []string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

// 添加货物
type AddGoodReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Good      *Good  `protobuf:"bytes,1,opt,name=good,proto3" json:"good,omitempty"`
	ClassName string `protobuf:"bytes,2,opt,name=className,proto3" json:"className,omitempty"`
}

func (x *AddGoodReq) Reset() {
	*x = AddGoodReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_pb_mvp_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddGoodReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGoodReq) ProtoMessage() {}

func (x *AddGoodReq) ProtoReflect() protoreflect.Message {
	mi := &file_common_pb_mvp_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGoodReq.ProtoReflect.Descriptor instead.
func (*AddGoodReq) Descriptor() ([]byte, []int) {
	return file_common_pb_mvp_proto_rawDescGZIP(), []int{9}
}

func (x *AddGoodReq) GetGood() *Good {
	if x != nil {
		return x.Good
	}
	return nil
}

func (x *AddGoodReq) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

type AddGoodRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddGoodRes) Reset() {
	*x = AddGoodRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_pb_mvp_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddGoodRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGoodRes) ProtoMessage() {}

func (x *AddGoodRes) ProtoReflect() protoreflect.Message {
	mi := &file_common_pb_mvp_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGoodRes.ProtoReflect.Descriptor instead.
func (*AddGoodRes) Descriptor() ([]byte, []int) {
	return file_common_pb_mvp_proto_rawDescGZIP(), []int{10}
}

type AddGoodClassReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodClass *GoodClass `protobuf:"bytes,1,opt,name=goodClass,proto3" json:"goodClass,omitempty"`
}

func (x *AddGoodClassReq) Reset() {
	*x = AddGoodClassReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_pb_mvp_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddGoodClassReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGoodClassReq) ProtoMessage() {}

func (x *AddGoodClassReq) ProtoReflect() protoreflect.Message {
	mi := &file_common_pb_mvp_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGoodClassReq.ProtoReflect.Descriptor instead.
func (*AddGoodClassReq) Descriptor() ([]byte, []int) {
	return file_common_pb_mvp_proto_rawDescGZIP(), []int{11}
}

func (x *AddGoodClassReq) GetGoodClass() *GoodClass {
	if x != nil {
		return x.GoodClass
	}
	return nil
}

type AddGoodClassRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddGoodClassRes) Reset() {
	*x = AddGoodClassRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_pb_mvp_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddGoodClassRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGoodClassRes) ProtoMessage() {}

func (x *AddGoodClassRes) ProtoReflect() protoreflect.Message {
	mi := &file_common_pb_mvp_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGoodClassRes.ProtoReflect.Descriptor instead.
func (*AddGoodClassRes) Descriptor() ([]byte, []int) {
	return file_common_pb_mvp_proto_rawDescGZIP(), []int{12}
}

type AddSpaceReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Space *Space `protobuf:"bytes,1,opt,name=space,proto3" json:"space,omitempty"`
}

func (x *AddSpaceReq) Reset() {
	*x = AddSpaceReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_pb_mvp_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddSpaceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSpaceReq) ProtoMessage() {}

func (x *AddSpaceReq) ProtoReflect() protoreflect.Message {
	mi := &file_common_pb_mvp_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSpaceReq.ProtoReflect.Descriptor instead.
func (*AddSpaceReq) Descriptor() ([]byte, []int) {
	return file_common_pb_mvp_proto_rawDescGZIP(), []int{13}
}

func (x *AddSpaceReq) GetSpace() *Space {
	if x != nil {
		return x.Space
	}
	return nil
}

type AddSpaceRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddSpaceRes) Reset() {
	*x = AddSpaceRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_pb_mvp_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddSpaceRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSpaceRes) ProtoMessage() {}

func (x *AddSpaceRes) ProtoReflect() protoreflect.Message {
	mi := &file_common_pb_mvp_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSpaceRes.ProtoReflect.Descriptor instead.
func (*AddSpaceRes) Descriptor() ([]byte, []int) {
	return file_common_pb_mvp_proto_rawDescGZIP(), []int{14}
}

type OrderGoodReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeskID int64   `protobuf:"varint,1,opt,name=deskID,proto3" json:"deskID,omitempty"`
	Goods  []*Good `protobuf:"bytes,2,rep,name=goods,proto3" json:"goods,omitempty"`
}

func (x *OrderGoodReq) Reset() {
	*x = OrderGoodReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_pb_mvp_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderGoodReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderGoodReq) ProtoMessage() {}

func (x *OrderGoodReq) ProtoReflect() protoreflect.Message {
	mi := &file_common_pb_mvp_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderGoodReq.ProtoReflect.Descriptor instead.
func (*OrderGoodReq) Descriptor() ([]byte, []int) {
	return file_common_pb_mvp_proto_rawDescGZIP(), []int{15}
}

func (x *OrderGoodReq) GetDeskID() int64 {
	if x != nil {
		return x.DeskID
	}
	return 0
}

func (x *OrderGoodReq) GetGoods() []*Good {
	if x != nil {
		return x.Goods
	}
	return nil
}

type OrderGoodRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OrderGoodRes) Reset() {
	*x = OrderGoodRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_pb_mvp_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderGoodRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderGoodRes) ProtoMessage() {}

func (x *OrderGoodRes) ProtoReflect() protoreflect.Message {
	mi := &file_common_pb_mvp_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderGoodRes.ProtoReflect.Descriptor instead.
func (*OrderGoodRes) Descriptor() ([]byte, []int) {
	return file_common_pb_mvp_proto_rawDescGZIP(), []int{16}
}

type OrderDeskReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpaceName string `protobuf:"bytes,1,opt,name=spaceName,proto3" json:"spaceName,omitempty"`
	SpaceNum  int64  `protobuf:"varint,2,opt,name=spaceNum,proto3" json:"spaceNum,omitempty"`
}

func (x *OrderDeskReq) Reset() {
	*x = OrderDeskReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_pb_mvp_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderDeskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDeskReq) ProtoMessage() {}

func (x *OrderDeskReq) ProtoReflect() protoreflect.Message {
	mi := &file_common_pb_mvp_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDeskReq.ProtoReflect.Descriptor instead.
func (*OrderDeskReq) Descriptor() ([]byte, []int) {
	return file_common_pb_mvp_proto_rawDescGZIP(), []int{17}
}

func (x *OrderDeskReq) GetSpaceName() string {
	if x != nil {
		return x.SpaceName
	}
	return ""
}

func (x *OrderDeskReq) GetSpaceNum() int64 {
	if x != nil {
		return x.SpaceNum
	}
	return 0
}

type OrderDeskRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeskID int64 `protobuf:"varint,1,opt,name=deskID,proto3" json:"deskID,omitempty"`
}

func (x *OrderDeskRes) Reset() {
	*x = OrderDeskRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_pb_mvp_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderDeskRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDeskRes) ProtoMessage() {}

func (x *OrderDeskRes) ProtoReflect() protoreflect.Message {
	mi := &file_common_pb_mvp_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDeskRes.ProtoReflect.Descriptor instead.
func (*OrderDeskRes) Descriptor() ([]byte, []int) {
	return file_common_pb_mvp_proto_rawDescGZIP(), []int{18}
}

func (x *OrderDeskRes) GetDeskID() int64 {
	if x != nil {
		return x.DeskID
	}
	return 0
}

type OrderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Order *Order `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
}

func (x *OrderReq) Reset() {
	*x = OrderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_pb_mvp_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderReq) ProtoMessage() {}

func (x *OrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_common_pb_mvp_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderReq.ProtoReflect.Descriptor instead.
func (*OrderReq) Descriptor() ([]byte, []int) {
	return file_common_pb_mvp_proto_rawDescGZIP(), []int{19}
}

func (x *OrderReq) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type OrderRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderID int64 `protobuf:"varint,1,opt,name=orderID,proto3" json:"orderID,omitempty"`
}

func (x *OrderRes) Reset() {
	*x = OrderRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_pb_mvp_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderRes) ProtoMessage() {}

func (x *OrderRes) ProtoReflect() protoreflect.Message {
	mi := &file_common_pb_mvp_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderRes.ProtoReflect.Descriptor instead.
func (*OrderRes) Descriptor() ([]byte, []int) {
	return file_common_pb_mvp_proto_rawDescGZIP(), []int{20}
}

func (x *OrderRes) GetOrderID() int64 {
	if x != nil {
		return x.OrderID
	}
	return 0
}

type CloseDeskReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeskID       int64 `protobuf:"varint,1,opt,name=deskID,proto3" json:"deskID,omitempty"`
	EndTimestamp int64 `protobuf:"varint,2,opt,name=endTimestamp,proto3" json:"endTimestamp,omitempty"`
}

func (x *CloseDeskReq) Reset() {
	*x = CloseDeskReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_pb_mvp_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloseDeskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseDeskReq) ProtoMessage() {}

func (x *CloseDeskReq) ProtoReflect() protoreflect.Message {
	mi := &file_common_pb_mvp_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseDeskReq.ProtoReflect.Descriptor instead.
func (*CloseDeskReq) Descriptor() ([]byte, []int) {
	return file_common_pb_mvp_proto_rawDescGZIP(), []int{21}
}

func (x *CloseDeskReq) GetDeskID() int64 {
	if x != nil {
		return x.DeskID
	}
	return 0
}

func (x *CloseDeskReq) GetEndTimestamp() int64 {
	if x != nil {
		return x.EndTimestamp
	}
	return 0
}

type CloseDeskRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CloseDeskRes) Reset() {
	*x = CloseDeskRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_pb_mvp_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloseDeskRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseDeskRes) ProtoMessage() {}

func (x *CloseDeskRes) ProtoReflect() protoreflect.Message {
	mi := &file_common_pb_mvp_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseDeskRes.ProtoReflect.Descriptor instead.
func (*CloseDeskRes) Descriptor() ([]byte, []int) {
	return file_common_pb_mvp_proto_rawDescGZIP(), []int{22}
}

type GetAllGoodClassesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllGoodClassesReq) Reset() {
	*x = GetAllGoodClassesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_pb_mvp_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllGoodClassesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllGoodClassesReq) ProtoMessage() {}

func (x *GetAllGoodClassesReq) ProtoReflect() protoreflect.Message {
	mi := &file_common_pb_mvp_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllGoodClassesReq.ProtoReflect.Descriptor instead.
func (*GetAllGoodClassesReq) Descriptor() ([]byte, []int) {
	return file_common_pb_mvp_proto_rawDescGZIP(), []int{23}
}

type GetAllGoodClassesRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodClasses []*GoodClass `protobuf:"bytes,1,rep,name=goodClasses,proto3" json:"goodClasses,omitempty"`
}

func (x *GetAllGoodClassesRes) Reset() {
	*x = GetAllGoodClassesRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_pb_mvp_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllGoodClassesRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllGoodClassesRes) ProtoMessage() {}

func (x *GetAllGoodClassesRes) ProtoReflect() protoreflect.Message {
	mi := &file_common_pb_mvp_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllGoodClassesRes.ProtoReflect.Descriptor instead.
func (*GetAllGoodClassesRes) Descriptor() ([]byte, []int) {
	return file_common_pb_mvp_proto_rawDescGZIP(), []int{24}
}

func (x *GetAllGoodClassesRes) GetGoodClasses() []*GoodClass {
	if x != nil {
		return x.GoodClasses
	}
	return nil
}

type GetDeskReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeskID int64 `protobuf:"varint,1,opt,name=deskID,proto3" json:"deskID,omitempty"`
}

func (x *GetDeskReq) Reset() {
	*x = GetDeskReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_pb_mvp_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDeskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeskReq) ProtoMessage() {}

func (x *GetDeskReq) ProtoReflect() protoreflect.Message {
	mi := &file_common_pb_mvp_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeskReq.ProtoReflect.Descriptor instead.
func (*GetDeskReq) Descriptor() ([]byte, []int) {
	return file_common_pb_mvp_proto_rawDescGZIP(), []int{25}
}

func (x *GetDeskReq) GetDeskID() int64 {
	if x != nil {
		return x.DeskID
	}
	return 0
}

type GetDeskRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Desk *Desk `protobuf:"bytes,1,opt,name=desk,proto3" json:"desk,omitempty"`
}

func (x *GetDeskRes) Reset() {
	*x = GetDeskRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_pb_mvp_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDeskRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeskRes) ProtoMessage() {}

func (x *GetDeskRes) ProtoReflect() protoreflect.Message {
	mi := &file_common_pb_mvp_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeskRes.ProtoReflect.Descriptor instead.
func (*GetDeskRes) Descriptor() ([]byte, []int) {
	return file_common_pb_mvp_proto_rawDescGZIP(), []int{26}
}

func (x *GetDeskRes) GetDesk() *Desk {
	if x != nil {
		return x.Desk
	}
	return nil
}

type CheckOutReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeskIDs []int64 `protobuf:"varint,1,rep,packed,name=deskIDs,proto3" json:"deskIDs,omitempty"`
	GoodIDs []int64 `protobuf:"varint,2,rep,packed,name=goodIDs,proto3" json:"goodIDs,omitempty"`
}

func (x *CheckOutReq) Reset() {
	*x = CheckOutReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_pb_mvp_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckOutReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckOutReq) ProtoMessage() {}

func (x *CheckOutReq) ProtoReflect() protoreflect.Message {
	mi := &file_common_pb_mvp_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckOutReq.ProtoReflect.Descriptor instead.
func (*CheckOutReq) Descriptor() ([]byte, []int) {
	return file_common_pb_mvp_proto_rawDescGZIP(), []int{27}
}

func (x *CheckOutReq) GetDeskIDs() []int64 {
	if x != nil {
		return x.DeskIDs
	}
	return nil
}

func (x *CheckOutReq) GetGoodIDs() []int64 {
	if x != nil {
		return x.GoodIDs
	}
	return nil
}

type CheckOutRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CheckOutRes) Reset() {
	*x = CheckOutRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_pb_mvp_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckOutRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckOutRes) ProtoMessage() {}

func (x *CheckOutRes) ProtoReflect() protoreflect.Message {
	mi := &file_common_pb_mvp_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckOutRes.ProtoReflect.Descriptor instead.
func (*CheckOutRes) Descriptor() ([]byte, []int) {
	return file_common_pb_mvp_proto_rawDescGZIP(), []int{28}
}

type AddElementReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Element   *Element `protobuf:"bytes,1,opt,name=element,proto3" json:"element,omitempty"`
	ClassName string   `protobuf:"bytes,2,opt,name=className,proto3" json:"className,omitempty"`
}

func (x *AddElementReq) Reset() {
	*x = AddElementReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_pb_mvp_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddElementReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddElementReq) ProtoMessage() {}

func (x *AddElementReq) ProtoReflect() protoreflect.Message {
	mi := &file_common_pb_mvp_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddElementReq.ProtoReflect.Descriptor instead.
func (*AddElementReq) Descriptor() ([]byte, []int) {
	return file_common_pb_mvp_proto_rawDescGZIP(), []int{29}
}

func (x *AddElementReq) GetElement() *Element {
	if x != nil {
		return x.Element
	}
	return nil
}

func (x *AddElementReq) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

type AddElementRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddElementRes) Reset() {
	*x = AddElementRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_pb_mvp_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddElementRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddElementRes) ProtoMessage() {}

func (x *AddElementRes) ProtoReflect() protoreflect.Message {
	mi := &file_common_pb_mvp_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddElementRes.ProtoReflect.Descriptor instead.
func (*AddElementRes) Descriptor() ([]byte, []int) {
	return file_common_pb_mvp_proto_rawDescGZIP(), []int{30}
}

var File_common_pb_mvp_proto protoreflect.FileDescriptor

var file_common_pb_mvp_proto_rawDesc = []byte{
	0x0a, 0x13, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x62, 0x2f, 0x6d, 0x76, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x7f, 0x0a, 0x0b, 0x45, 0x78, 0x70,
	0x65, 0x6e, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x28, 0x0a, 0x0f, 0x6e, 0x6f, 0x6e, 0x46,
	0x61, 0x76, 0x6f, 0x72, 0x45, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x0f, 0x6e, 0x6f, 0x6e, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x45, 0x78, 0x70, 0x65, 0x6e,
	0x73, 0x65, 0x12, 0x2c, 0x0a, 0x11, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x4f, 0x75, 0x74, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x63,
	0x68, 0x65, 0x63, 0x6b, 0x4f, 0x75, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x12, 0x18, 0x0a, 0x07, 0x65, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x07, 0x65, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x22, 0x8b, 0x01, 0x0a, 0x05, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x6b, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x52, 0x04, 0x64, 0x65,
	0x73, 0x6b, 0x12, 0x21, 0x0a, 0x06, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x52, 0x06, 0x66,
	0x61, 0x76, 0x6f, 0x72, 0x73, 0x12, 0x31, 0x0a, 0x0b, 0x65, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e,
	0x45, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b, 0x65, 0x78, 0x70,
	0x65, 0x6e, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0xf9, 0x01, 0x0a, 0x04, 0x44, 0x65, 0x73,
	0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x1f, 0x0a, 0x05, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x70, 0x61, 0x63, 0x65, 0x52, 0x05, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x22, 0x0a, 0x0c, 0x65, 0x6e,
	0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0c, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1e,
	0x0a, 0x05, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e,
	0x70, 0x62, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x52, 0x05, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x12, 0x21,
	0x0a, 0x06, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09,
	0x2e, 0x70, 0x62, 0x2e, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x52, 0x06, 0x66, 0x61, 0x76, 0x6f, 0x72,
	0x73, 0x12, 0x31, 0x0a, 0x0b, 0x65, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x78, 0x70, 0x65,
	0x6e, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b, 0x65, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x22, 0xd0, 0x01, 0x0a, 0x04, 0x47, 0x6f, 0x6f, 0x64, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2d, 0x0a,
	0x0b, 0x6d, 0x61, 0x69, 0x6e, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x0b, 0x6d, 0x61, 0x69, 0x6e, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x33, 0x0a, 0x0e,
	0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x0e, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x73, 0x12, 0x21, 0x0a, 0x06, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x52, 0x06, 0x66, 0x61,
	0x76, 0x6f, 0x72, 0x73, 0x12, 0x31, 0x0a, 0x0b, 0x65, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x45,
	0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b, 0x65, 0x78, 0x70, 0x65,
	0x6e, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x7c, 0x0a, 0x05, 0x53, 0x70, 0x61, 0x63, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x37, 0x0a, 0x0d,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x52, 0x75, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x75,
	0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0d, 0x70, 0x72, 0x69, 0x63, 0x65, 0x52, 0x75, 0x6c,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x3f, 0x0a, 0x09, 0x47, 0x6f, 0x6f, 0x64, 0x43, 0x6c, 0x61,
	0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x05, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x52,
	0x05, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x22, 0x6e, 0x0a, 0x07, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x2a, 0x0a, 0x09, 0x73, 0x69,
	0x7a, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x70, 0x62, 0x2e, 0x53, 0x69, 0x7a, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x73, 0x69, 0x7a,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x22, 0x80, 0x01, 0x0a, 0x08, 0x53, 0x69, 0x7a, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x2a, 0x0a,
	0x10, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x50, 0x61, 0x74,
	0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65,
	0x53, 0x74, 0x6f, 0x72, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x73, 0x53,
	0x65, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x69,
	0x73, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x22, 0x54, 0x0a, 0x05, 0x46, 0x61, 0x76,
	0x6f, 0x72, 0x12, 0x2b, 0x0a, 0x09, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x61, 0x76, 0x6f, 0x72,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x1e, 0x0a, 0x0a, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x22,
	0x48, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x47, 0x6f, 0x6f, 0x64, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a,
	0x04, 0x67, 0x6f, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62,
	0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x52, 0x04, 0x67, 0x6f, 0x6f, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x63,
	0x6c, 0x61, 0x73, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x63, 0x6c, 0x61, 0x73, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x0c, 0x0a, 0x0a, 0x41, 0x64, 0x64,
	0x47, 0x6f, 0x6f, 0x64, 0x52, 0x65, 0x73, 0x22, 0x3e, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x47, 0x6f,
	0x6f, 0x64, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x52, 0x65, 0x71, 0x12, 0x2b, 0x0a, 0x09, 0x67, 0x6f,
	0x6f, 0x64, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x70, 0x62, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x52, 0x09, 0x67, 0x6f,
	0x6f, 0x64, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x22, 0x11, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x47, 0x6f,
	0x6f, 0x64, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x52, 0x65, 0x73, 0x22, 0x2e, 0x0a, 0x0b, 0x41, 0x64,
	0x64, 0x53, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1f, 0x0a, 0x05, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x70,
	0x61, 0x63, 0x65, 0x52, 0x05, 0x73, 0x70, 0x61, 0x63, 0x65, 0x22, 0x0d, 0x0a, 0x0b, 0x41, 0x64,
	0x64, 0x53, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x73, 0x22, 0x46, 0x0a, 0x0c, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x47, 0x6f, 0x6f, 0x64, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x73,
	0x6b, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x64, 0x65, 0x73, 0x6b, 0x49,
	0x44, 0x12, 0x1e, 0x0a, 0x05, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x52, 0x05, 0x67, 0x6f, 0x6f, 0x64,
	0x73, 0x22, 0x0e, 0x0a, 0x0c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x47, 0x6f, 0x6f, 0x64, 0x52, 0x65,
	0x73, 0x22, 0x48, 0x0a, 0x0c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x65, 0x73, 0x6b, 0x52, 0x65,
	0x71, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x70, 0x61, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x70, 0x61, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x73, 0x70, 0x61, 0x63, 0x65, 0x4e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x73, 0x70, 0x61, 0x63, 0x65, 0x4e, 0x75, 0x6d, 0x22, 0x26, 0x0a, 0x0c, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x44, 0x65, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x64,
	0x65, 0x73, 0x6b, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x64, 0x65, 0x73,
	0x6b, 0x49, 0x44, 0x22, 0x2b, 0x0a, 0x08, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12,
	0x1f, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09,
	0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x22, 0x24, 0x0a, 0x08, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x49, 0x44, 0x22, 0x4a, 0x0a, 0x0c, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x44,
	0x65, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x73, 0x6b, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x64, 0x65, 0x73, 0x6b, 0x49, 0x44, 0x12, 0x22,
	0x0a, 0x0c, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x22, 0x0e, 0x0a, 0x0c, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x44, 0x65, 0x73, 0x6b, 0x52,
	0x65, 0x73, 0x22, 0x16, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x47, 0x6f, 0x6f, 0x64,
	0x43, 0x6c, 0x61, 0x73, 0x73, 0x65, 0x73, 0x52, 0x65, 0x71, 0x22, 0x47, 0x0a, 0x14, 0x47, 0x65,
	0x74, 0x41, 0x6c, 0x6c, 0x47, 0x6f, 0x6f, 0x64, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x12, 0x2f, 0x0a, 0x0b, 0x67, 0x6f, 0x6f, 0x64, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x6f, 0x6f,
	0x64, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x52, 0x0b, 0x67, 0x6f, 0x6f, 0x64, 0x43, 0x6c, 0x61, 0x73,
	0x73, 0x65, 0x73, 0x22, 0x24, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x44, 0x65, 0x73, 0x6b, 0x52, 0x65,
	0x71, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x73, 0x6b, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x64, 0x65, 0x73, 0x6b, 0x49, 0x44, 0x22, 0x2a, 0x0a, 0x0a, 0x47, 0x65, 0x74,
	0x44, 0x65, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x6b, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x52,
	0x04, 0x64, 0x65, 0x73, 0x6b, 0x22, 0x41, 0x0a, 0x0b, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x4f, 0x75,
	0x74, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x73, 0x6b, 0x49, 0x44, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x07, 0x64, 0x65, 0x73, 0x6b, 0x49, 0x44, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x67, 0x6f, 0x6f, 0x64, 0x49, 0x44, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03, 0x52,
	0x07, 0x67, 0x6f, 0x6f, 0x64, 0x49, 0x44, 0x73, 0x22, 0x0d, 0x0a, 0x0b, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x22, 0x54, 0x0a, 0x0d, 0x41, 0x64, 0x64, 0x45, 0x6c,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x25, 0x0a, 0x07, 0x65, 0x6c, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x45,
	0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x07, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12,
	0x1c, 0x0a, 0x09, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x0f, 0x0a,
	0x0d, 0x41, 0x64, 0x64, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x2a, 0x3f,
	0x0a, 0x09, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4e,
	0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x45, 0x42, 0x41, 0x54, 0x45, 0x10,
	0x01, 0x12, 0x12, 0x0a, 0x0e, 0x46, 0x55, 0x4c, 0x4c, 0x5f, 0x52, 0x45, 0x44, 0x55, 0x43, 0x54,
	0x49, 0x4f, 0x4e, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x52, 0x45, 0x45, 0x10, 0x03, 0x2a,
	0x24, 0x0a, 0x0d, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x75, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x08, 0x0a, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x10, 0x01, 0x2a, 0x23, 0x0a, 0x0b, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4d, 0x61, 0x69, 0x6e, 0x10, 0x00, 0x12, 0x0a,
	0x0a, 0x06, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x10, 0x01, 0x32, 0x81, 0x04, 0x0a, 0x03, 0x4d,
	0x76, 0x70, 0x12, 0x47, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x47, 0x6f, 0x6f, 0x64,
	0x43, 0x6c, 0x61, 0x73, 0x73, 0x65, 0x73, 0x12, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74,
	0x41, 0x6c, 0x6c, 0x47, 0x6f, 0x6f, 0x64, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x1a, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x47, 0x6f, 0x6f,
	0x64, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x65, 0x73, 0x52, 0x65, 0x73, 0x12, 0x38, 0x0a, 0x0c, 0x41,
	0x64, 0x64, 0x47, 0x6f, 0x6f, 0x64, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x13, 0x2e, 0x70, 0x62,
	0x2e, 0x41, 0x64, 0x64, 0x47, 0x6f, 0x6f, 0x64, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x52, 0x65, 0x71,
	0x1a, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x64, 0x64, 0x47, 0x6f, 0x6f, 0x64, 0x43, 0x6c, 0x61,
	0x73, 0x73, 0x52, 0x65, 0x73, 0x12, 0x29, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x47, 0x6f, 0x6f, 0x64,
	0x12, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x64, 0x64, 0x47, 0x6f, 0x6f, 0x64, 0x52, 0x65, 0x71,
	0x1a, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x64, 0x64, 0x47, 0x6f, 0x6f, 0x64, 0x52, 0x65, 0x73,
	0x12, 0x32, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x11,
	0x2e, 0x70, 0x62, 0x2e, 0x41, 0x64, 0x64, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x1a, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x64, 0x64, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x12, 0x2c, 0x0a, 0x08, 0x41, 0x64, 0x64, 0x53, 0x70, 0x61, 0x63, 0x65,
	0x12, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65,
	0x71, 0x1a, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x70, 0x61, 0x63, 0x65, 0x52,
	0x65, 0x73, 0x12, 0x2f, 0x0a, 0x09, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x47, 0x6f, 0x6f, 0x64, 0x12,
	0x10, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x47, 0x6f, 0x6f, 0x64, 0x52, 0x65,
	0x71, 0x1a, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x47, 0x6f, 0x6f, 0x64,
	0x52, 0x65, 0x73, 0x12, 0x2f, 0x0a, 0x09, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x65, 0x73, 0x6b,
	0x12, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x65, 0x73, 0x6b, 0x52,
	0x65, 0x71, 0x1a, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x65, 0x73,
	0x6b, 0x52, 0x65, 0x73, 0x12, 0x29, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x44, 0x65, 0x73, 0x6b, 0x12,
	0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x1a,
	0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x12,
	0x2f, 0x0a, 0x09, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x44, 0x65, 0x73, 0x6b, 0x12, 0x10, 0x2e, 0x70,
	0x62, 0x2e, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x44, 0x65, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x10,
	0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x44, 0x65, 0x73, 0x6b, 0x52, 0x65, 0x73,
	0x12, 0x2c, 0x0a, 0x08, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x4f, 0x75, 0x74, 0x12, 0x0f, 0x2e, 0x70,
	0x62, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e,
	0x70, 0x62, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_pb_mvp_proto_rawDescOnce sync.Once
	file_common_pb_mvp_proto_rawDescData = file_common_pb_mvp_proto_rawDesc
)

func file_common_pb_mvp_proto_rawDescGZIP() []byte {
	file_common_pb_mvp_proto_rawDescOnce.Do(func() {
		file_common_pb_mvp_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_pb_mvp_proto_rawDescData)
	})
	return file_common_pb_mvp_proto_rawDescData
}

var file_common_pb_mvp_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_common_pb_mvp_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_common_pb_mvp_proto_goTypes = []interface{}{
	(FavorType)(0),               // 0: pb.FavorType
	(PriceRuleType)(0),           // 1: pb.PriceRuleType
	(ElementType)(0),             // 2: pb.ElementType
	(*ExpenseInfo)(nil),          // 3: pb.ExpenseInfo
	(*Order)(nil),                // 4: pb.Order
	(*Desk)(nil),                 // 5: pb.Desk
	(*Good)(nil),                 // 6: pb.Good
	(*Space)(nil),                // 7: pb.Space
	(*GoodClass)(nil),            // 8: pb.GoodClass
	(*Element)(nil),              // 9: pb.Element
	(*SizeInfo)(nil),             // 10: pb.SizeInfo
	(*Favor)(nil),                // 11: pb.Favor
	(*AddGoodReq)(nil),           // 12: pb.AddGoodReq
	(*AddGoodRes)(nil),           // 13: pb.AddGoodRes
	(*AddGoodClassReq)(nil),      // 14: pb.AddGoodClassReq
	(*AddGoodClassRes)(nil),      // 15: pb.AddGoodClassRes
	(*AddSpaceReq)(nil),          // 16: pb.AddSpaceReq
	(*AddSpaceRes)(nil),          // 17: pb.AddSpaceRes
	(*OrderGoodReq)(nil),         // 18: pb.OrderGoodReq
	(*OrderGoodRes)(nil),         // 19: pb.OrderGoodRes
	(*OrderDeskReq)(nil),         // 20: pb.OrderDeskReq
	(*OrderDeskRes)(nil),         // 21: pb.OrderDeskRes
	(*OrderReq)(nil),             // 22: pb.OrderReq
	(*OrderRes)(nil),             // 23: pb.OrderRes
	(*CloseDeskReq)(nil),         // 24: pb.CloseDeskReq
	(*CloseDeskRes)(nil),         // 25: pb.CloseDeskRes
	(*GetAllGoodClassesReq)(nil), // 26: pb.GetAllGoodClassesReq
	(*GetAllGoodClassesRes)(nil), // 27: pb.GetAllGoodClassesRes
	(*GetDeskReq)(nil),           // 28: pb.GetDeskReq
	(*GetDeskRes)(nil),           // 29: pb.GetDeskRes
	(*CheckOutReq)(nil),          // 30: pb.CheckOutReq
	(*CheckOutRes)(nil),          // 31: pb.CheckOutRes
	(*AddElementReq)(nil),        // 32: pb.AddElementReq
	(*AddElementRes)(nil),        // 33: pb.AddElementRes
}
var file_common_pb_mvp_proto_depIdxs = []int32{
	5,  // 0: pb.Order.desk:type_name -> pb.Desk
	11, // 1: pb.Order.favors:type_name -> pb.Favor
	3,  // 2: pb.Order.expenseInfo:type_name -> pb.ExpenseInfo
	7,  // 3: pb.Desk.space:type_name -> pb.Space
	6,  // 4: pb.Desk.goods:type_name -> pb.Good
	11, // 5: pb.Desk.favors:type_name -> pb.Favor
	3,  // 6: pb.Desk.expenseInfo:type_name -> pb.ExpenseInfo
	9,  // 7: pb.Good.mainElement:type_name -> pb.Element
	9,  // 8: pb.Good.attachElements:type_name -> pb.Element
	11, // 9: pb.Good.favors:type_name -> pb.Favor
	3,  // 10: pb.Good.expenseInfo:type_name -> pb.ExpenseInfo
	1,  // 11: pb.Space.priceRuleType:type_name -> pb.PriceRuleType
	6,  // 12: pb.GoodClass.goods:type_name -> pb.Good
	2,  // 13: pb.Element.type:type_name -> pb.ElementType
	10, // 14: pb.Element.sizeInfos:type_name -> pb.SizeInfo
	0,  // 15: pb.Favor.FavorType:type_name -> pb.FavorType
	6,  // 16: pb.AddGoodReq.good:type_name -> pb.Good
	8,  // 17: pb.AddGoodClassReq.goodClass:type_name -> pb.GoodClass
	7,  // 18: pb.AddSpaceReq.space:type_name -> pb.Space
	6,  // 19: pb.OrderGoodReq.goods:type_name -> pb.Good
	4,  // 20: pb.OrderReq.order:type_name -> pb.Order
	8,  // 21: pb.GetAllGoodClassesRes.goodClasses:type_name -> pb.GoodClass
	5,  // 22: pb.GetDeskRes.desk:type_name -> pb.Desk
	9,  // 23: pb.AddElementReq.element:type_name -> pb.Element
	26, // 24: pb.Mvp.GetAllGoodClasses:input_type -> pb.GetAllGoodClassesReq
	14, // 25: pb.Mvp.AddGoodClass:input_type -> pb.AddGoodClassReq
	12, // 26: pb.Mvp.AddGood:input_type -> pb.AddGoodReq
	32, // 27: pb.Mvp.AddElement:input_type -> pb.AddElementReq
	16, // 28: pb.Mvp.AddSpace:input_type -> pb.AddSpaceReq
	18, // 29: pb.Mvp.OrderGood:input_type -> pb.OrderGoodReq
	20, // 30: pb.Mvp.OrderDesk:input_type -> pb.OrderDeskReq
	28, // 31: pb.Mvp.GetDesk:input_type -> pb.GetDeskReq
	24, // 32: pb.Mvp.CloseDesk:input_type -> pb.CloseDeskReq
	30, // 33: pb.Mvp.CheckOut:input_type -> pb.CheckOutReq
	27, // 34: pb.Mvp.GetAllGoodClasses:output_type -> pb.GetAllGoodClassesRes
	15, // 35: pb.Mvp.AddGoodClass:output_type -> pb.AddGoodClassRes
	13, // 36: pb.Mvp.AddGood:output_type -> pb.AddGoodRes
	33, // 37: pb.Mvp.AddElement:output_type -> pb.AddElementRes
	17, // 38: pb.Mvp.AddSpace:output_type -> pb.AddSpaceRes
	19, // 39: pb.Mvp.OrderGood:output_type -> pb.OrderGoodRes
	21, // 40: pb.Mvp.OrderDesk:output_type -> pb.OrderDeskRes
	29, // 41: pb.Mvp.GetDesk:output_type -> pb.GetDeskRes
	25, // 42: pb.Mvp.CloseDesk:output_type -> pb.CloseDeskRes
	31, // 43: pb.Mvp.CheckOut:output_type -> pb.CheckOutRes
	34, // [34:44] is the sub-list for method output_type
	24, // [24:34] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_common_pb_mvp_proto_init() }
func file_common_pb_mvp_proto_init() {
	if File_common_pb_mvp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_pb_mvp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExpenseInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_pb_mvp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Order); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_pb_mvp_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Desk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_pb_mvp_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Good); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_pb_mvp_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Space); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_pb_mvp_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoodClass); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_pb_mvp_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Element); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_pb_mvp_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SizeInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_pb_mvp_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Favor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_pb_mvp_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddGoodReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_pb_mvp_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddGoodRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_pb_mvp_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddGoodClassReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_pb_mvp_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddGoodClassRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_pb_mvp_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddSpaceReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_pb_mvp_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddSpaceRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_pb_mvp_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderGoodReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_pb_mvp_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderGoodRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_pb_mvp_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderDeskReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_pb_mvp_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderDeskRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_pb_mvp_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_pb_mvp_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_pb_mvp_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloseDeskReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_pb_mvp_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloseDeskRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_pb_mvp_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllGoodClassesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_pb_mvp_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllGoodClassesRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_pb_mvp_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDeskReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_pb_mvp_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDeskRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_pb_mvp_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckOutReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_pb_mvp_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckOutRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_pb_mvp_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddElementReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_pb_mvp_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddElementRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_pb_mvp_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_pb_mvp_proto_goTypes,
		DependencyIndexes: file_common_pb_mvp_proto_depIdxs,
		EnumInfos:         file_common_pb_mvp_proto_enumTypes,
		MessageInfos:      file_common_pb_mvp_proto_msgTypes,
	}.Build()
	File_common_pb_mvp_proto = out.File
	file_common_pb_mvp_proto_rawDesc = nil
	file_common_pb_mvp_proto_goTypes = nil
	file_common_pb_mvp_proto_depIdxs = nil
}
