drop table if exists `good_class`;
drop table if exists `good`;
drop table if exists `element`;
drop table if exists `main_element_attach_element_record`;
drop table if exists `element_size_record`;
drop table if exists `desk`;
drop table if exists `space`;
drop table if exists `order`;
drop table if exists `favor_record`;
